name: CubicCountdown
version: 1.1-BETA
main: de.timecoding.cc.CubicCountdown
api-version: 1.13
softdepend: [PlaceholderAPI]
description: "A plugin which is able to start a countdown when a cube is full of blocks"

commands:
  cubiccountdown:
    aliases:
      - cc
    description: "A command which allows players to do the CubicCountdown setup"
